### ISSUE TITLE
Automatic code checks

### ISSUE THREAD

**Issue by PeteHaitch** [Shians/CellBench#1]
I think it's worth running `goodpractice::goodpractice(".")` and `BiocCheck::BiocCheck(".")` (I won't post the output here since it's rather long). 
Some of the warnings are spurious/premature since the package is still in development (e.g. lack of unit tests) but others are worth fixing now (e.g., use `seq_len()` or `seq_along()` instead of `1:N`).

Overally, I take these more as indicators than rules. But you'll ultimately need to satisfy **BiocCheck** for submission to Bioconductor.

**Comment by Shians** [comment]
BiocCheck compliance achieved in 00abb86.
