### ISSUE TITLE
vignette ‘Introduction’ not found 

### ISSUE THREAD

**Issue by lovivi** [Shians/CellBench#8]
vignette("Introduction", package = "CellBench") 
Warning message:
vignette ‘Introduction’ not found 

Where can I find more detailed documentation, it does not seem to find the associated instance in the .rmd of the related ‘CellBench_data’ project.

**Comment by Shians** [comment]
Thanks for taking interest in this package, if you installed from Github you may not have the vignettes, it should be present if you install from Bioconductor. As for more detailed documentation, I am planning to write some more next week to bridge the gap between this repository and the CellBench_data repository.

**Comment by lovivi** [comment]
Thanks for your reply. This may be due to the fact that I added fewer parameters when installing without "build_opts = c("--no-resave-data", "--no-manual"))". Your function is very easy to use, especially the idea of streaming this way, and I have improved a lot of my code like yours. But the script of  CellBench_data project has lots of error path and complex dependency, that cost much time to solve them.
